# Next.js GitLab CI Configuration

stages:
  - sonar
  - deploy

# Sonar stage (original configuration restored)
sonar:
  stage: sonar
  script:
    - source /etc/environment
    - sonar-scanner -Dsonar.projectKey=scubed-landing-page -Dsonar.sources=. -Dsonar.host.url=$sonar_host -Dsonar.login=$sonar_login
  only:
    - develop

# Deploy to development on AWS Amplify
deploy_web:
  stage: deploy
  image: node:18-alpine
  environment:
    name: dev
  before_script:
    - apk add --no-cache aws-cli curl
    - echo NEXT_PUBLIC_ADMIN_APP_URL=$NEXT_PUBLIC_ADMIN_APP_URL >> .env.local
    - echo NEXT_PUBLIC_ADMIN_APP_API_URL=$NEXT_PUBLIC_ADMIN_APP_API_URL >> .env.local
    - echo NEXT_PUBLIC_SITE_URL=$NEXT_PUBLIC_SITE_URL >> .env.local
    - echo NEXT_PUBLIC_FACEBOOK_URL=$NEXT_PUBLIC_FACEBOOK_URL >> .env.local
    - echo NEXT_PUBLIC_INSTAGRAM_URL=$NEXT_PUBLIC_INSTAGRAM_URL >> .env.local
    - echo NEXT_PUBLIC_YOUTUBE_URL=$NEXT_PUBLIC_YOUTUBE_URL >> .env.local
    - echo NEXT_PUBLIC_PHONE_NUMBER=$NEXT_PUBLIC_PHONE_NUMBER >> .env.local
    - echo NEXT_PUBLIC_EMAIL=$NEXT_PUBLIC_EMAIL >> .env.local
    - echo NEXT_PUBLIC_ADDRESS=$NEXT_PUBLIC_ADDRESS >> .env.local
    - echo NEXT_PUBLIC_GOOGLE_SITE_VERIFICATION=$NEXT_PUBLIC_GOOGLE_SITE_VERIFICATION >> .env.local
    - echo NEXT_PUBLIC_GTM_ID=$NEXT_PUBLIC_GTM_ID >> .env.local
    - echo NEXT_PUBLIC_CALENDLY_URL=$NEXT_PUBLIC_CALENDLY_URL >> .env.local
    - echo NEXT_PUBLIC_LINKEDIN_URL=$NEXT_PUBLIC_LINKEDIN_URL >> .env.local
  script:
    - npm ci
    - npm run build
    # Trigger Amplify deployment for development
    - aws amplify start-job --app-id $AMPLIFY_APP_ID_DEV --branch-name develop --job-type RELEASE --region $AWS_REGION
    - echo "Deployment triggered for Amplify App ID: $AMPLIFY_APP_ID_DEV"
    - >
      curl -X POST -H "Content-Type: application/json" 
      -d "{\"text\": \"${MESSAGE_DEV}\"}" 
      "${GCHAT_WEBHOOK_URL}"
  when: manual
  only:
    - develop

# Deploy to staging on AWS Amplify
deploy_web_staging:
  stage: deploy
  image: node:18-alpine
  environment:
    name: stage
  before_script:
    - apk add --no-cache aws-cli curl
    - echo NEXT_PUBLIC_ADMIN_APP_URL=$NEXT_PUBLIC_ADMIN_APP_URL >> .env.local
    - echo NEXT_PUBLIC_ADMIN_APP_API_URL=$NEXT_PUBLIC_ADMIN_APP_API_URL >> .env.local
    - echo NEXT_PUBLIC_SITE_URL=$NEXT_PUBLIC_SITE_URL >> .env.local
    - echo NEXT_PUBLIC_FACEBOOK_URL=$NEXT_PUBLIC_FACEBOOK_URL >> .env.local
    - echo NEXT_PUBLIC_INSTAGRAM_URL=$NEXT_PUBLIC_INSTAGRAM_URL >> .env.local
    - echo NEXT_PUBLIC_YOUTUBE_URL=$NEXT_PUBLIC_YOUTUBE_URL >> .env.local
    - echo NEXT_PUBLIC_PHONE_NUMBER=$NEXT_PUBLIC_PHONE_NUMBER >> .env.local
    - echo NEXT_PUBLIC_EMAIL=$NEXT_PUBLIC_EMAIL >> .env.local
    - echo NEXT_PUBLIC_ADDRESS=$NEXT_PUBLIC_ADDRESS >> .env.local
    - echo NEXT_PUBLIC_GOOGLE_SITE_VERIFICATION=$NEXT_PUBLIC_GOOGLE_SITE_VERIFICATION >> .env.local
    - echo NEXT_PUBLIC_GTM_ID=$NEXT_PUBLIC_GTM_ID >> .env.local
    - echo NEXT_PUBLIC_CALENDLY_URL=$NEXT_PUBLIC_CALENDLY_URL >> .env.local
    - echo NEXT_PUBLIC_LINKEDIN_URL=$NEXT_PUBLIC_LINKEDIN_URL >> .env.local
  script:
    - npm ci
    - npm run build
    # Trigger Amplify deployment for staging
    - aws amplify start-job --app-id $AMPLIFY_APP_ID_STAGING --branch-name staging --job-type RELEASE --region $AWS_REGION
    - echo "Deployment triggered for Amplify App ID: $AMPLIFY_APP_ID_STAGING"
    - >
      curl -X POST -H "Content-Type: application/json" 
      -d "{\"text\": \"${MESSAGE_STAGE}\"}" 
      "${GCHAT_WEBHOOK_URL}"
  when: manual
  only:
    - staging

# Deploy to production on AWS Amplify
deploy_web_prod:
  stage: deploy
  image: node:18-alpine
  environment:
    name: prod
  before_script:
    - apk add --no-cache aws-cli curl
    - echo NEXT_PUBLIC_ADMIN_APP_URL=$NEXT_PUBLIC_ADMIN_APP_URL >> .env.local
    - echo NEXT_PUBLIC_ADMIN_APP_API_URL=$NEXT_PUBLIC_ADMIN_APP_API_URL >> .env.local
    - echo NEXT_PUBLIC_SITE_URL=$NEXT_PUBLIC_SITE_URL >> .env.local
    - echo NEXT_PUBLIC_FACEBOOK_URL=$NEXT_PUBLIC_FACEBOOK_URL >> .env.local
    - echo NEXT_PUBLIC_INSTAGRAM_URL=$NEXT_PUBLIC_INSTAGRAM_URL >> .env.local
    - echo NEXT_PUBLIC_YOUTUBE_URL=$NEXT_PUBLIC_YOUTUBE_URL >> .env.local
    - echo NEXT_PUBLIC_PHONE_NUMBER=$NEXT_PUBLIC_PHONE_NUMBER >> .env.local
    - echo NEXT_PUBLIC_EMAIL=$NEXT_PUBLIC_EMAIL >> .env.local
    - echo NEXT_PUBLIC_ADDRESS=$NEXT_PUBLIC_ADDRESS >> .env.local
    - echo NEXT_PUBLIC_GOOGLE_SITE_VERIFICATION=$NEXT_PUBLIC_GOOGLE_SITE_VERIFICATION >> .env.local
    - echo NEXT_PUBLIC_GTM_ID=$NEXT_PUBLIC_GTM_ID >> .env.local
    - echo NEXT_PUBLIC_CALENDLY_URL=$NEXT_PUBLIC_CALENDLY_URL >> .env.local
    - echo NEXT_PUBLIC_LINKEDIN_URL=$NEXT_PUBLIC_LINKEDIN_URL >> .env.local
  script:
    - npm ci
    - npm run build
    # Trigger Amplify deployment for production
    - aws amplify start-job --app-id $AMPLIFY_APP_ID_PROD --branch-name main --job-type RELEASE --region $AWS_REGION
    - echo "Deployment triggered for Amplify App ID: $AMPLIFY_APP_ID_PROD"
    - >
      curl -X POST -H "Content-Type: application/json" 
      -d "{\"text\": \"${MESSAGE_PROD}\"}" 
      "${GCHAT_WEBHOOK_URL}"
  when: manual
  only:
    - master
    - main

